### ISSUE TITLE
still can be opened with SQLite Browser

### ISSUE THREAD

**Issue by azn1viet** [litehelpers/Cordova-sqlcipher-adapter#10]
It seemed not encrypted anything since it's still readable by SQLite Browser

**Comment by brodybits** [comment]
Please make sure you are using a valid key to encrypt the database. A key of zero length (`''`) will cause your data to be stored without encryption. If you continue to see the issue it would help if you can make a demo project to demonstrate the issue.

**Comment by azn1viet** [comment]
name: "my.db", key: "your-password-here", it does not create a db nor give me any error messages!

**Comment by brodybits** [comment]
Beware that the Android database file will be hidden from other applications. Will be documented when I get a chance.

**Comment by azn1viet** [comment]
I was testing on iOS and look for the db in IExplorer. The app is hung at the db creation process.

**Comment by azn1viet** [comment]
I tried this: not working

Supported way: var db = window.sqlitePlugin.openDatabase({name: "my.db", key: "your-password-here", location: 1});

This classical way: working but not encrypted

var db = window.sqlitePlugin.openDatabase("myDatabase.db", "1.0", "Demo", -1);

**Comment by brodybits** [comment]
Please be sure that you try this on a fresh project, and try it without the "location: 1" option. If it does not work it would really help me if you can post a test project to reproduce the problem.

**Comment by azn1viet** [comment]
I got it worked now. Thanks for the excellent plugin. But I think we need to also encrypt the key: "your-password-here" in case users can extract the app and get this password to decrypt the db.

**Comment by brodybits** [comment]
Normally you should get the key from the user input. If you want to encrypt your own data so that the user cannot access it, then you would have to hide your key somehow.
