### ISSUE TITLE
I have an improvement: Type check on constructor object.

### ISSUE THREAD

**Issue by Silom** [litehelpers/Cordova-sqlcipher-adapter#14]
Hello,
I was searching for a bug a very long time, and I think this is a huge pitfall the JS community can meet here.

Simple: I had a number as password and there was no error, instead there was nothing.
Only appears on IOS.

Suggestion:
```
SQLitePlugin.prototype.open = function (success, error) {
  ....
  /*
  If this.openargs has any wrong types, the plugin wont give a callback.
  In my case the password was a number, caused by an encryption lib I was using it returned a number which I used to encrypt.

  Right above this comment there could be a type check, which would remove this pitfall.
  */
  cordova.exec(opensuccesscb, openerrorcb, "SQLitePlugin", "open", [this.openargs]);
  ....
};
```

**Comment by brodybits** [comment]
Thanks for reporting. This is similar to litehelpers/Cordova-sqlite-storage#246 / litehelpers/Cordova-sqlcipher-adapter#5 where ngcordova would use the options object in the name field (which has now been fixed). My solution to litehelpers/Cordova-sqlite-storage#246 / litehelpers/Cordova-sqlcipher-adapter#5 is to simply throw an error if the name field is not a string, and I will probably apply the same solution for the password field.

**Comment by brodybits** [comment]
This is now fixed.
