### ISSUE TITLE
What is Windows "Universal" (8.1) ?

### ISSUE THREAD

**Issue by Watabe08** [litehelpers/Cordova-sqlcipher-adapter#16]
Hello there,

I am a translator who happens to work on the doc related to this plugin.

In your doc, you are using this word "Windows Universal 8.1". Does this mean that "Windows 8.1 + Windows Phone 8.1" ?
Or any other thing? 

It is lovely to know what you mean.

Thanks you for your advice in advance.

**Comment by brodybits** [comment]
> In your doc, you are using this word "Windows Universal 8.1". Does this
mean that "Windows 8.1 + Windows Phone 8.1" ?

Both Windows 8.1 (or greater) and Windows Phone 8.1 (or greater).

Microsoft had made a Windows "Universal" label for applications that run on
both Windows desktop and Windows mobile (along with Windows tablets of
course), then they dropped the label. For Windows 8.1 and Windows Phone
8.1, the JavaScript can be the same but each separate native libraries had
to be built for Windows desktop and Windows Mobile. Windows 10 supports
running the same native libs on both desktop and mobile but I have not
gotten there yet.

**Comment by Watabe08** [comment]
Chris,

Thanks for the quick reply.

Yep, that solves all my problems and now I understand why you put "" to
enclose the word universal like "universal".

Again, thanks a lot.

tks,

Watabe

2015-11-19 15:38 GMT+09:00 Chris Brody <notifications@github.com>:
