### ISSUE TITLE
Android: Cursor not closed explicitly

### ISSUE THREAD

**Issue by ergovia-mobile** [litehelpers/Cordova-sqlcipher-adapter#2]
Hi,

we frequently get logging output indicating the cursors not getting closed on Android Devices. They occur every time we do several transactions in a row. All the transactions are handled just fine, no errors. But maybe these lines lead to something that can be improved. Thanks for your time.

```
03-27 14:12:24.920: W/SQLiteCompiledSql(31066): Releasing statement in a finalizer. Please ensure that you explicitly call close() on your cursor: INSERT INTO foo (bar, bar2, bar3 
03-27 14:12:24.920: W/SQLiteCompiledSql(31066): net.sqlcipher.database.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
03-27 14:12:24.920: W/SQLiteCompiledSql(31066): 	at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:62)
03-27 14:12:24.920: W/SQLiteCompiledSql(31066): 	at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:103)
03-27 14:12:24.920: W/SQLiteCompiledSql(31066): 	at net.sqlcipher.database.SQLiteStatement.<init>(SQLiteStatement.java:39)
03-27 14:12:24.920: W/SQLiteCompiledSql(31066): 	at net.sqlcipher.database.SQLiteDatabase.compileStatement(SQLiteDatabase.java:1241)
03-27 14:12:24.920: W/SQLiteCompiledSql(31066): 	at org.pgsqlite.SQLitePlugin.executeSqlBatch(SQLitePlugin.java:427)
03-27 14:12:24.920: W/SQLiteCompiledSql(31066): 	at org.pgsqlite.SQLitePlugin.access$100(SQLitePlugin.java:40)
03-27 14:12:24.920: W/SQLiteCompiledSql(31066): 	at org.pgsqlite.SQLitePlugin$DBRunner.run(SQLitePlugin.java:702)
03-27 14:12:24.920: W/SQLiteCompiledSql(31066): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
03-27 14:12:24.920: W/SQLiteCompiledSql(31066): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
03-27 14:12:24.920: W/SQLiteCompiledSql(31066): 	at java.lang.Thread.run(Thread.java:856)

```

**Comment by stormtek** [comment]
I have noticed this while working on getting an Android version of our app working as well.

**Comment by johnnypark** [comment]
Any news on this?

**Comment by petetandon** [comment]
see http://stackoverflow.com/a/32744405/794088

**Comment by johnnypark** [comment]
Yep, that looks quite good. In SQLitePlugin.java I inserted `myStatement.close();` in line 438 and no more error messages so far.
Brody, what do you think?

**Comment by brodybits** [comment]
This seems to be fixed by PR #15. I will check it and merge it if it looks OK when I get a chance.

**Comment by ergovia-mobile** [comment]
I can confirm that my test case runs without an error. :+1:

**Comment by brodybits** [comment]
#15 is now merged, closing.

**Comment by brodybits** [comment]
From #15:
>> @brodybits it appears this PR had been accidentally reverted when you merged 'common-regexp-src' into cipher-rc ec5b50c
>> 
>> Any chance of this fix being re-applied?

> My apologies, I will reapply the fix when I get a chance. It will probably be a few weeks since I am busy with a couple of urgent projects right now. I will reopen #2 and #3 until I reapply the fix.

**Comment by brodybits** [comment]
The fix is now applied.

**Comment by petetandon** [comment]
Yay!
