### ISSUE TITLE
WKWebView incompatible

### ISSUE THREAD

**Issue by azn1viet** [litehelpers/Cordova-sqlcipher-adapter#22]
The older engine on iOS using UIWebKit which is fine but it's slow on Cordova apps. I'm about upgrading the new iOS engine called WKWebView which can reduce 50-80% memory usage. However, the big issue is I can't open SQLite db anymore. Anyone can tell me if you're successful using this plugin to open the db?

**Comment by brodybits** [comment]
Sorry for the delay. Similar issues have been reported with Web SQL (built-in sqlite). It would be good to test this with Cordova-sqlite-storage (core version, uses built-in sqlite3 library) and cordova-sqlite-ext (includes rebuild of sqlite3) as well.

**Comment by azn1viet** [comment]
This will be a big issue in iOS 10. Please read the case testing below:

-  iPhone 6, iOS 10, xCode 8, target iOS 10: UIWebView can't render the app
-  iPhone 6, iOS 10, xCode 8, target iOS 10 + WKWebView: app rendered so fast , can't open  SQLite
- iPhone 6, iOS 10, xCode 7.3.1, **target iOS 9**: make an Ad-hoc app: UIWebView can run, performance slow.

Will do more tests with Cordova-sqlite-storage alone and post it here later.

**Comment by brodybits** [comment]
Thanks @azn1viet. Unfortunately I will not have a chance to look at this before December 2016. Can you confirm:

Did you mean that you have trouble using Web SQL in WKWebView, using this version with WKWebView, or both?

"iOS 10: UIWebView can't render the app": do you mean that iOS 10 with UIWebView cannot render an app with this plugin, that iOS with UIWebView cannot render an app at all, or something else?

It would be great if you have a chance to test a brand new Cordova app, with or without Cordova-sqlite-storage or this version, in the various target combinations. I also published https://github.com/brodybits/Cordova-sqlite-bootstrap-test as a simple starting point for testing.

**Comment by azn1viet** [comment]
_- Did you mean that you have trouble using Web SQL in WKWebView, using this version with WKWebView, or both?_
_- "iOS 10: UIWebView can't render the app": do you mean that iOS 10 with UIWebView cannot render an app with this plugin, that iOS with UIWebView cannot render an app at all, or something else?_

- This plugin can't be used in WKWebView at all. This plugin can't be used even with UIWebView in iOS 10. But it can be used with iOS lower than 10 (6-9) with UIWebView.

Yes, I will do more test with "Cordova-sqlite-storage" later on.

Thanks.

**Comment by azn1viet** [comment]
For Cordova-sqlite-storage, it appears to be the same as this plugin:

- UIWebView: db can be opened on iOS 6-9, not on 10
- WKWebView: can't open db at all.

Thanks.

**Comment by brodybits** [comment]
This issue will be handled in litehelpers/Cordova-sqlite-storage#567 (iOS 10 support) and litehelpers/Cordova-sqlite-storage#567 (iOS WKWebView support).

**Comment by brodybits** [comment]
See https://github.com/litehelpers/Cordova-sqlite-storage/issues/567#issuecomment-250598993:
> With Xcode 8.1 beta it works for me if I do cordova prepare before attempting to run on iOS 10.1 (simulator). Please confirm if this helps or not.

**Comment by brodybits** [comment]
@azn1viet I have tested both the main Cordova-sqlite-storage and this project on iOS 10.1 emulator with the normal UIWebView, 9.3 (emulator) with WKWebView (cordova-plugin-wkwebview-engine), and 10.1 emulator with WKWebView. These cases all work if I do `cordova prepare` before attempting to build and run. I will document this when I get a chance. Closing for now, please report in litehelpers/Cordova-sqlite-storage#567 (iOS 10 support) or litehelpers/Cordova-sqlite-storage#568 (use with WKWebView) if you continue to encounter this issue.

**Comment by azn1viet** [comment]
Thank you.  I never use cordova prepare command. Not sure how it works but
per cordova website, it copies files to a structure directory which is I
think the same way I use cordova platform add ... .Btw, I'll try that and
report again.

Thanks.

**Comment by azn1viet** [comment]
database = window.sqlitePlugin.openDatabase({name: 'sample.db', key: 'test', iosDatabaseLocation: 'Documents'}, successcb, errorcb);

-  ", successcb, errorcb" option: caused the DB not open in iOS 10, remove it and it works fine for both UIWebView engine and WKWebView engine 

So could you have a look at ", successcb, errorcb" option?
