### ISSUE TITLE
Not able to install the plugin through cordova commands

### ISSUE THREAD

**Issue by manishm77** [litehelpers/Cordova-sqlcipher-adapter#27]
We are not able to download (install) the plugin through the below cordova command.

 cordova plugin add https://github.com/litehelpers/Cordova-sqlcipher-adapter 

 Command does not give an error but plugin does not install.

**Comment by brodybits** [comment]
Please check the `plugins` subdirectory of your project.

You may need to do `cordova prepare`.

**Comment by manishm77** [comment]
I am able to install the plugin now.
