### ISSUE TITLE
Windows: error C4996: 'fopen': This function or variable may be unsafe.

### ISSUE THREAD

**Issue by sgrebnov** [litehelpers/Cordova-sqlcipher-adapter#34]
```
c:\temp\sqlcipher\plugins\cordova-sqlcipher-adapter\src\common\sqlite3.c(17959): error C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_S ECURE_NO_WARNINGS. See online help for details. [C:\temp\sqlCipher\plugins\cordova-sqlcipher-adapter\src\windows\SQLite3-Win-RT\SQLite3\SQLite3.UWP\SQLite3.UWP.vcxproj]
```

Looks like this is due to the following change

https://github.com/litehelpers/Cordova-sqlcipher-adapter/commit/af3d1ed7c49366b02e26a123c947f26d7f132d3c

**Comment by brodybits** [comment]
The quick workaround is to add a flag to `src/windows/SQLite3-Win-RT/SQLite3/SQLite3.Shared.vcxitems` to define `_CRT_SECURE_NO_WARNINGS`. The correct solution is to get this fixed in the upstream SQLCipher source. I will deal with this when I get a chance in the next couple weeks or so.

**Comment by sgrebnov** [comment]
Great, thanks! Maybe it makes sense to temporary update sqlite3.c so it will be overridden with correct version during next update?

Change
```
#if defined(_WIN32) && (__STDC_VERSION__ > 199901L)
    if(fopen_s(&f, destination, "a") != 0){
#else
    f = fopen(destination, "a");
    if(f == 0){
#endif
```
To
```
#if defined(_WIN32) && (__STDC_VERSION__ > 199901L) || defined(SQLITE_OS_WINRT)
    if(fopen_s(&f, destination, "a") != 0){
#else
    f = fopen(destination, "a");
    if(f == 0){
#endif
```

**Comment by sgrebnov** [comment]
Otherwise we can forgot to remove  temporary added '_CRT_SECURE_NO_WARNINGS' flag. Or this is fine?

**Comment by brodybits** [comment]
I have mixed feelings about this. On the one hand I like the quick solution that does not edit code until we get this resolved. On the other hand I would favor test with the solution that will be published in the future.

I will raise an issue on the SQLCipher project that this is still an issue and maybe you can jump into the discussion to help get this resolved.

**Comment by sgrebnov** [comment]
Sounds good! This is fine as I'm not blocked and can work on #30 Replace libTomCrypt with OpenSSL crypto library in Windows version

**Comment by brodybits** [comment]
I just filed https://github.com/sqlcipher/sqlcipher/issues/174 to get this fixed upstream. I am happy to hear that you are not blocked.

**Comment by brodybits** [comment]
Fixed and fixed upstream
