### ISSUE TITLE
Android Nougat: Detected problems with app native libraries

### ISSUE THREAD

**Issue by ergovia-mobile** [litehelpers/Cordova-sqlcipher-adapter#41]
Hi, 

we just upgrade our Nexus 9 to Android N and now get the following popup while working with our app:

![libraryproblem](https://cloud.githubusercontent.com/assets/8656734/18080700/e386ec34-6e96-11e6-9faa-3139683de468.png)

The log file says:
`08-30 09:06:58.573: W/linker(3898): library "libutils.so" ("/system/lib/libutils.so") needed or dlopened by "/data/app/de.ergovia.our.app/lib/arm/libsqlcipher_android.so" is not accessible for the namespace "classloader-namespace" - the access is temporarily granted as a workaround for http://b/26394120, note that the access will be removed in future releases of Android.`

The [changelog](https://developer.android.com/about/versions/nougat/android-7.0-changes.html#ndk) paragraph "NDK Apps Linking to Platform Libraries" has some info about this matter. 

Nougat is still very fresh, just thinking this information may be of some value to you.
thx for looking into this :)

The app is working flawlessly apart from the popup ;)

**Comment by Silom** [comment]
Can confirm.

**Comment by brodybits** [comment]
Guys please double-check that you are using the latest release. It should already be solved.

For reference:
- sqlcipher/android-database-sqlcipher#216 (now fixed)
- https://discuss.zetetic.net/t/sqlcipher-for-android-release-android-n-support/1465

**Comment by ergovia-mobile** [comment]
Apologies, the issue is indeed fiexed in the latest version.

**Comment by brodybits** [comment]
Thanks. @Silom please report if it still does not work after the update.

**Comment by Silom** [comment]
@brodybits can confirm fix. Sorry.. had - as you said - an older version running.

**Comment by brodybits** [comment]
Thanks @Silom. I will document the requirement to use a recent version when I get a chance. Reopened to track this.

**Comment by ma-pe** [comment]
Hey, 
I also upgraded the version from 0.1.4rc to 0.1.7 in order to fix the described bug. 

That worked...
...but: I am getting Errors Reading from tables of databases that were created with earlier versions of my app (with plugin 0.1.4rc). 

Doing a "Select *" statement results in an "get field slot from row 0 col 0 failed" on Android and gives me an empty result on ios.

I tried to localize the problem by updating step by step.

0.1.4rc (current version in my app) - android & ios working fine
0.1.5 - android works, ios fails
0.1.6 - both fail
0.1.7 - both fail

**Comment by brodybits** [comment]
Hi @ma-pe,

There are a few things that could help me reproduce your issue:

It is possible to wait for the sqlitePlugin.openDatabase success or error callback. It would be great if you can confirm which callback you receive.

It would also be really helpful if you could post a very simple test program that demonstrates how you could create a database with 0.1.4-rc and then could not open it with a newer version.

Can you raise a new issue with this information included?

Thanks,
Chris

**Comment by ma-pe** [comment]
Everything I do is done in the success-callback of openDatabase.

The sequence is about this:

openDatabase
Create table a if not exists 
Create table b if not exists
Select * from table a

=> Android: "get field slot from row 0 col 0 failed"
=> iOS: Empty result

I look forward to post a test program if i find some time today...

**Comment by PrafulGH** [comment]
Updated to Android 7 on Nexus 6P

Android security patch level : 6 September 2016
Baseband version : angler-03.72
kernel  version : 3.10.73-gde1f200
Build number : NRD90U

Still I get this annoying pop up message on my app
"Detected problems with app native libraries
(please consult log for detail:
libiconv.so:text relocations
libzbarjni.so:text relocations)"

Please guide on what am I missing

Thanks

**Comment by brodybits** [comment]
@PrafulGH please do `cordova plugin ls` and check the version. The current version is `0.1.7`. Please upgrade if your version is behind.

**Comment by dineshreddy36** [comment]
"Detected problems with app native libraries
(please consult log for detail:
libiconv.so:text relocations
libzbarjni.so:text relocations)"

Please guide on what am I missing

Thanks

**Comment by brodybits** [comment]
> "Detected problems with app native libraries
> (please consult log for detail:
> libiconv.so:text relocations
> libzbarjni.so:text relocations)"

Please double-check that you have the latest version.

**Comment by dineshreddy36** [comment]
Can you please elaborate what do you mean by latest version?

**Comment by brodybits** [comment]
Please do `cordova plugin ls` and check what it shows for cordova-sqlcipher-adapter. The latest version is `0.1.8`. If you have an earlier version please use `cordova plugin rm` to remove it and then do `cordova plugin add cordova-sqlcipher-adapter --save` to add it again.

**EXTRA TIP:** If you add **all** cordova plugins with the `--save` flag they will be tracked in `config.xml`.

**Comment by shangtianhao** [comment]
啥鸡巴玩意儿啊
