### ISSUE TITLE
Plugin-Update from 0.1.4-rc to 0.1.7 resulting in Incompatibility

### ISSUE THREAD

**Issue by ma-pe** [litehelpers/Cordova-sqlcipher-adapter#42]
I am experiencing problems after updating the plugin with databases that were created with earlier versions.

In my case I was updating from 0.1.4-rc to 0.1.7 in order to solve this issue regarding Android 7: https://github.com/litehelpers/Cordova-sqlcipher-adapter/issues/41

That worked...
...but: I am getting Errors Reading from tables of databases that were created with earlier versions of my app (with plugin 0.1.4rc).

Doing a "Select *" statement results in an "get field slot from row 0 col 0 failed" on Android and gives me an empty result on ios.

I tried to localize the problem by updating step by step.

0.1.4rc (current version in my app) - android & ios working fine
0.1.5 - android works, ios fails
0.1.6 - both fail
0.1.7 - both fail

I did update the default-location from "2" to "default" which should be the same. Correct me if I'm wrong. If I do a fresh install of the app - everything works like a charm... but well... we need the users existing database.

Everything I do is done in the success-callback of openDatabase.

The sequence is about this:

openDatabase
Create table a if not exists 
Create table b if not exists
Select \* from table b

=> Android: "get field slot from row 0 col 0 failed"
=> iOS: Empty result

I look forward to post a test program today...

**Comment by brodybits** [comment]
@ma-pe is this still an issue? Do you have a simple test program?

**Comment by ma-pe** [comment]
Hey @brodybits, I tried to reproduce with a simple program but couldn't. We moved this issue to our next release and I will soon be analyzing it further. Most likely there is something wrong with my code, but I would leave the issue open until I manage to give more information.

**Comment by brodybits** [comment]
Please report if this is still an issue or not.

**Comment by ma-pe** [comment]
This is no issue anymore. It just turned up on one test-device (reproducable). After a clear install of the app and updating then to the newer version of sqlcipher-adapter everything went fine.

I don't know what it was, but it just happened in one combination of device and preexisting data.

**Comment by brody2consult** [comment]
Closing as invalid
