### ISSUE TITLE
Include SQLCipher 3.4.1

### ISSUE THREAD

**Issue by brodybits** [litehelpers/Cordova-sqlcipher-adapter#48]
ref: <https://discuss.zetetic.net/t/sqlcipher-3-4-1-release/1962>

FYI this should provide slightly better consistency with cordova-sqlite-storage which is now using sqlite 3.15.2.

**Comment by maxpowa** [comment]
Will this fix the 1MB cursor limit as mentioned in [this issue](https://github.com/sqlcipher/android-database-sqlcipher/issues/47#issuecomment-279817948) and/or [this issue](https://github.com/litehelpers/Cordova-sqlcipher-adapter/issues/46) and/or [this issue](https://github.com/litehelpers/Cordova-sqlcipher-adapter/issues/37)?

**Comment by brodybits** [comment]
> Will this fix the 1MB cursor limit as mentioned in [this issue (sqlcipher/android-database-sqlcipher#47)](https://github.com/sqlcipher/android-database-sqlcipher/issues/47)

To clarify: SQLCipher 3.4.1 would actually be a part of SQLCipher for Android 3.5.6, which does fix the 1MB cursor limit in that library. But:

> and/or [this issue (litehelpers/Cordova-sqlcipher-adapter#46)](https://github.com/litehelpers/Cordova-sqlcipher-adapter/issues/46) and/or [this issue (litehelpers/Cordova-sqlcipher-adapter#37)](https://github.com/litehelpers/Cordova-sqlcipher-adapter/issues/37)?

I cannot say for sure. These issues may also be related to litehelpers/Cordova-sqlite-storage#474 (maximum length of TEXT field).

**Comment by brodybits** [comment]
SQLCipher 3.4.1 is now included, along with a special build of SQLCipher for Android 3.5.6.
