### ISSUE TITLE
Check if db name is a string [Name of the database on android contains the key]

### ISSUE THREAD

**Issue by Honza-R** [litehelpers/Cordova-sqlcipher-adapter#5]
I have looked at where the database is stored on android and to my surprise the file name is the whole object passed as the argument on opening the database, it is for command
`var db = window.sqlitePlugin.openDatabase({name: "my.db", key: "your-password-here", location: 1});`

the name of the file containing the database is 
`{name: "my.db", key: "your-password-here", location: 1}`

instead of `my.db` I expected. Exposing the key this way makes the encryption useless.

The same applies to the sqlite plugin, the file name is again the whole json jstring.

**Comment by brodybits** [comment]
Hi can you explain how you made this conclusion? Looking at the code I cannot see how this may be possible.

**Comment by Honza-R** [comment]
It is the file name I see in a file manager on the phone, in the databases directory of the app data folder (accessible only with root rights).

**Comment by brodybits** [comment]
Can I bother you to post a screenshot?

**Comment by Honza-R** [comment]
Here it is
![screenshot_2015-04-22-22-37-48](https://cloud.githubusercontent.com/assets/12073173/7284851/a737e4a4-e940-11e4-9e25-4c898bb24b2b.png)

**Comment by brodybits** [comment]
This is still not enough information for me to reproduce the issue. It would really help if you can use `adb logcat` to get the log and take a look (the plugin will log the file name that you attempt to open).

To be honest, I am starting to suspect that something in your application code may be converting a Javascript "JSON" object to a string, which is in turn interpreted by sqlitePlugin.openDatabase() as a file name. I suggest you check the argument(s) very carefully that you pass to sqlitePlugin.openDatabase().

If you continue to see this problem persist:
- specify which version of Cordova you see this on and whether you see the issue on an emulator, device, or both, along with the Anrdroid OS version
- then please try to isolate the smallest test program you can make to reproduce the issue. You can either post it or send it directly to me at brodybits@litehelpers.net

**Comment by Honza-R** [comment]
I have realized I am calling the plugin via a ngCordova wrapper and the error is there - they collect the first argument and pass it to your plugin as the name of the database, alhough in the example in the documentation, the argument is the same as calling the plugin directly (http://ngcordova.com/docs/plugins/sqlite/). 

I will try to fix my code tonight but I think you can consider this solved - it is clear where the problem is.

**Comment by brodybits** [comment]
> I have realized I am calling the plugin via a ngCordova wrapper and the
> error is there - they collect the first argument and pass it to your plugin
> as the name of the database, alhough in the example in the documentation,
> the argument is the same as calling the plugin directly
> (http://ngcordova.com/docs/plugins/sqlite/).

Yes and that's a classic when source code and documentation diverge. Also the link in http://ngcordova.com/docs/plugins/sqlite/ to the source code is broken-for the record the related source code is at: https://github.com/driftyco/ng-cordova/blob/master/src/plugins/sqlite.js

> I will try to fix my code tonight but I think you can consider this solved -
> it is clear where the problem is.

Yes and no ("Yein"). The plugin really *should* check that the database name given is really a string and *not* a Javascript object that *could* be turned into a string.

> Sorry for posting the issue at a wrong place.

Disagreed-this kind of report can really help improve the quality-datatype should be checked as stated above. Will be fixed in both sqlite and sqlcipher versions when I get a chance.

**Comment by Honza-R** [comment]
I have just tried calling the sqlcipher plugin directly and everything works as it should. I'm going to report the problem (at least in documentation) to ngCordova developers.

**Comment by brodybits** [comment]
This is now fixed.
