### ISSUE TITLE
Could not open database

### ISSUE THREAD

**Issue by Kirancloudnix** [litehelpers/Cordova-sqlcipher-adapter#53]
My code is 
`var db = window.sqlitePlugin.openDatabase({name: "d2a.db", location: 1},function(success){ console.log(success); },function(error){ console.log(error); });`

My log is below:
new transaction is waiting for open operation
plugins/cordova-sqlite-storage/www/SQLitePlugin.js:197 OPEN database: d2a.db FAILED, aborting any pending transactions
static/js/d2a-sqlite.js:148 Error: Could not open database
    at newSQLError (plugins/cordova-sqlite-storage/www/SQLitePlugin.js:26)
    at plugins/cordova-sqlite-storage/www/SQLitePlugin.js:199
    at Object.callbackFromNative (cordova.js:295)
    at <anonymous>:1:9
static/js/d2a-sqlite.js:194 transaction error: Invalid database handle

**Comment by Kirancloudnix** [comment]
@joenoon @rafaelbeckel @purplecabbage

**Comment by brody2consult** [comment]
My apologies for the delay, looks like you either have the wrong plugin installed (cordova-sqlite-storage) or have multiple sqlite/sqlcipher plugins installed. Closing as invalid. Please use cordova-sqlite-help with more complete test program in case of this kind of an issue.
