### ISSUE TITLE
Ratchet CSS can't display correctly and cant navigate to other page

### ISSUE THREAD

**Issue by JimmyNgUNITEN** [litehelpers/Cordova-sqlcipher-adapter#61]
Hi, I am using cordova to build a mobile application but i having a problem with navigation/link to other pages. Is there any suggestion for me. Thanks in advance
[https://stackoverflow.com/questions/47439120/ratchet-css-cant-display-correctly-and-cant-navigate-to-other-page](url)

**Comment by brodybits** [comment]
CSS frameworks are not supported here. For Cordova sqlite questions please ask in <https://github.com/litehelpers/Cordova-sqlite-help/issues>. Also <https://github.com/apache/cordova-discuss/issues> may be good for quick Q&A.

Commercial support is available by contacting <sales@litehelpers.net>.
