### ISSUE TITLE
Not working on cordova-android@7, should use AAR (Gradle)

### ISSUE THREAD

**Issue by brodybits** [litehelpers/Cordova-sqlcipher-adapter#64]
As reported in litehelpers/Cordova-sqlite-storage#729 this plugin will not work on cordova-android@7, which is standard for latest Cordova CLI (8.0.0). The best solution would be to include SQLCipher for Android using Gradle. I would like to resolve this when supporting SQLCipher 3.4.2 / 3.5.8 (#62).

**Comment by brody2consult** [comment]
And thanks for guidance to: <https://stackoverflow.com/questions/34115571/add-external-jar-library-to-build-cordova-plugin-ionic-framework/34129929#34129929> (accepted answer)
